---
abstract: 'Data::Page for JavaScript'
author:
  - 'Leon Brocard <acme@astray.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JS-Data-Page
provides:
  JS::Data::Page:
    file: lib/JS/Data/Page.pm
    version: 0.02
requires:
  File::ShareDir: 1.00
  JS: 0
resources:
  homepage: http://search.cpan.org/dist/JS-Data-Page/
  license: http://dev.perl.org/licenses/
version: 0.02
